[package]
name = "AzureNexus"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tun2 = { version = "3", features = ["async"] }
rand = "0.8.4"
tokio-tun = "0.12.0"
ring = "0.17.8"
trust-dns-resolver = "0.23.2"
prost = "0.13.3"
